name: merge-main-into-small-image.yml
on:
  pull_request:
    branches:
      - main   
    types:
      - closed
jobs:
  merge-main-into-small-image:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    timeout-minutes: 3
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: name: Merge main into small-image

on:
  pull_request:
    types: [closed]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Merge main into small-image
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git checkout small-image
          git merge main
          git push origin small-
      run: |
        git config user.Arrisom github-actions
        git config user.162399161+arrisatom@users.noreply.github.com
        git fetch
        git checkout small-image
        git merge main --no-ff --no-edit
        git push origin small-image
